### ISSUE TITLE
landscaper-cli components-cli fails with parsing component-descriptor

### ISSUE THREAD

**Issue by DenisDuev** [gardener/landscapercli#66]
I have followed the docs here: https://github.com/gardener/landscapercli/blob/master/docs/commands/create_component/create.md#22-add-an-application-provided-as-local-helm-chart

**What happened**:
After executing:
```
landscaper-cli components-cli component-archive resources add \
   $LS_COMPONENT_DIR/demo-component \
   -r $LS_COMPONENT_DIR/demo-component/resources.yaml
```

I get warnings and errors:
```
Flag --resource has been deprecated, the flag r is deprecated use command args instead
unable to parse component archive from /repo/test/demo-component: unable to parse component descriptor read from component-descriptor.yaml: component.name: Does not match pattern '^[a-z0-9.\-]+[.][a-z]{2,4}/[-a-z0-9/_.]*$'
```

**What you expected to happen**:
1. In the docs to have a command with the right argument (as `-r` is deprecated)
2. The name of my component descriptor is: `github.com/DenisDuev/landscaper-manifest-action/test` which the regex `^[a-z0-9.\-]+[.][a-z]{2,4}/[-a-z0-9/_.]*$` do not match. The capital letters in the username are problematic. Is this mandatory or missed regex expression?

**How to reproduce it (as minimally and precisely as possible)**:
have a name of the component-descriptor containing capital letters, follow the docs.

**Comment by achimweigel** [comment]
We have corrected the documentation and added a check with respect to the component name such that you get an error if it does not match the regex from above. The rules expressed by the regex are mandatory because other tools included in the landscaper-cli like the component-cli requires such naming conventions. 

The fix will be included in the next release but you could get it immediately if you clone the project and call `make install-cli`.
